### ISSUE TITLE
pagerduty_team_membership crashes during terraform import

### ISSUE THREAD

**Issue by raeder1986** [PagerDuty/terraform-provider-pagerduty#504]
Good day! During `terraform import` for `pagerduty_team_membership` resource crashes

### Terraform Version
`Terraform v1.1.9`

### Affected Resource(s)
`pagerduty_team_membership`

### Terraform Configuration Files
```
resource "pagerduty_team_membership" "Acceptance" {
  role    = "acc"
  team_id = "XTEAMIDX"
  user_id = "XUSERIDX"
}
```

### Output
```
terraform import "pagerduty_team_membership.Acceptance" XUSERIDX.XTEAMIDX
pagerduty_team_membership.Acceptance: Importing from ID "XUSERIDX.XTEAMIDX"...
pagerduty_team_membership.Acceptance: Import prepared!
  Prepared pagerduty_team_membership for import
pagerduty_team_membership.Acceptance: Refreshing state... [id=XUSERIDX.XTEAMIDX]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-pagerduty_v2.2.1.exe plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 73 [running]:
github.com/terraform-providers/terraform-provider-pagerduty/pagerduty.resourcePagerDutyTeamMembershipParseID(...)
        github.com/terraform-providers/terraform-provider-pagerduty/pagerduty/resource_pagerduty_team_membership.go:173
github.com/terraform-providers/terraform-provider-pagerduty/pagerduty.fetchPagerDutyTeamMembership(0xc0007c3280, 0xe93840, 0xc0002409a0, 0x10237d8, 0xc0003a08f0, 0x16164a11768)
        github.com/terraform-providers/terraform-provider-pagerduty/pagerduty/resource_pagerduty_team_membership.go:50 +0x3af
github.com/terraform-providers/terraform-provider-pagerduty/pagerduty.resourcePagerDutyTeamMembershipRead(0xc0007c3280, 0xe93840, 0xc0002409a0, 0xc00023e750, 0x1842240)
        github.com/terraform-providers/terraform-provider-pagerduty/pagerduty/resource_pagerduty_team_membership.go:110 +0x52
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000895c00, 0x122a388, 0xc000390e00, 0xc0007c3280, 0xe93840, 0xc0002409a0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:335 +0x1fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000895c00, 0x122a388, 0xc000390e00, 0xc000240fc0, 0xe93840, 0xc0002409a0, 0xc00028af38, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000298000, 0x122a388, 0xc000390e00, 0xc000390e40, 0xc000390e00, 0x24bf6a, 0xf3d880)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/grpc_provider.go:575 +0x45b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0003fc3a0, 0x122a430, 0xc000390e00, 0xc00023cc00, 0xc0003fc3a0, 0xc000252750, 0xc00053dba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x108
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0xf84100, 0xc0003fc3a0, 0x122a430, 0xc000252750, 0xc00023cba0, 0x0, 0x122a430, 0xc000252750, 0xc00003cae0, 0x5d)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004bec40, 0x1234cd8, 0xc0003de600, 0xc0003b6300, 0xc00038ca20, 0x1831430, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.33.2/server.go:1210 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0004bec40, 0x1234cd8, 0xc0003de600, 0xc0003b6300, 0x0)
        google.golang.org/grpc@v1.33.2/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000881e0, 0xc0004bec40, 0x1234cd8, 0xc0003de600, 0xc0003b6300)
        google.golang.org/grpc@v1.33.2/server.go:871 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.33.2/server.go:869 +0x1fd

Error: The terraform-provider-pagerduty_v2.2.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
### Expected Behavior
State for resource should be imported

### Actual Behavior
Plugin did not respond

### Checked verions of plugin
2.4.0, 2.4.1, 2.2.1

**Comment by stmcallister** [comment]
Hey @raeder1986 ! Sorry for the delay! It looks like your import is using a `.` syntax when the [documentation](https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/team_membership#import) calls for a `:` syntax in the import statement. So, in your case your import statement should look something like this.

`terraform import "pagerduty_team_membership.Acceptance" XUSERIDX:XTEAMIDX`

Going to close. Please reopen if you continue to experience issues. Thanks!
